apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWko3RmFDVzd2d1l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp>
    server: https://AD6CE6619154CCA17E39B8A3FF3E9772.yl4.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:051826694723:cluster/my-eks-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:051826694723:cluster/my-eks-cluster
    user: arn:aws:eks:us-east-1:051826694723:cluster/my-eks-cluster
  name: arn:aws:eks:us-east-1:051826694723:cluster/my-eks-cluster
current-context: arn:aws:eks:us-east-1:051826694723:cluster/my-eks-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:051826694723:cluster/my-eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - my-eks-cluster
      command: aws


#       cd
# mv kubectl kubectl_1.24
# mv bin bin_1.24 
# curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.15/2023-01-11/bin/linux/amd64/kubectl
# chmod +x ./kubectl
# mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
# kubectl version

## To view workloads of cluster in eks UI, give arn in aws auth config:
# kubectl edit configmap -n kube-system aws-auth
# mapUsers: |
#     - userarn: arn:aws:iam::051826694723:root
#       username: admin
#       groups:
#         - system:masters